name: deploy netlify

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout master
      uses: actions/checkout@master

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.16'

    - name: install
      run: npm ci

    - name: Build
      run: npm run build
#     env:
#       PUBLIC_URL: 

    - name: Deploy
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=./build --functions=function
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
